// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./role";
export * from "./rolesMapping";

// Import resources to register:
import { Role } from "./role";
import { RolesMapping } from "./rolesMapping";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "elasticsearch:opensearch/role:Role":
                return new Role(name, <any>undefined, { urn })
            case "elasticsearch:opensearch/rolesMapping:RolesMapping":
                return new RolesMapping(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("elasticsearch", "opensearch/role", _module)
pulumi.runtime.registerResourceModule("elasticsearch", "opensearch/rolesMapping", _module)
