# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .index import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import oko-press_pulumi-elasticsearch.config as __config
    config = __config
else:
    config = _utilities.lazy_import('oko-press_pulumi-elasticsearch.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "elasticsearch",
  "mod": "index/index",
  "fqn": "oko-press_pulumi-elasticsearch",
  "classes": {
   "elasticsearch:index/index:Index": "Index"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "elasticsearch",
  "token": "pulumi:providers:elasticsearch",
  "fqn": "oko-press_pulumi-elasticsearch",
  "class": "Provider"
 }
]
"""
)
