// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace opensearch {
    export interface RoleIndexPermission {
        allowedActions?: pulumi.Input<pulumi.Input<string>[]>;
        documentLevelSecurity?: pulumi.Input<string>;
        fieldLevelSecurities?: pulumi.Input<pulumi.Input<string>[]>;
        indexPatterns?: pulumi.Input<pulumi.Input<string>[]>;
        maskedFields?: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface RoleTenantPermission {
        allowedActions?: pulumi.Input<pulumi.Input<string>[]>;
        tenantPatterns?: pulumi.Input<pulumi.Input<string>[]>;
    }
}
