// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace opensearch {
    export interface RoleIndexPermission {
        allowedActions?: string[];
        documentLevelSecurity?: string;
        fieldLevelSecurities?: string[];
        indexPatterns?: string[];
        maskedFields?: string[];
    }

    export interface RoleTenantPermission {
        allowedActions?: string[];
        tenantPatterns?: string[];
    }

}
